-- Create tables for Stage 2 and Stage 3 requests
create table if not exists public."Solicitud_2" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  numero_operacion text,
  nombre text, -- Name of the document requested
  estado text default 'Pendiente', -- 'Pendiente' or 'Completado'
  url text -- URL of the uploaded document
);

create table if not exists public."Solicitud_3" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  numero_operacion text,
  nombre text,
  estado text default 'Pendiente',
  url text
);

-- Enable RLS
alter table public."Solicitud_2" enable row level security;
alter table public."Solicitud_3" enable row level security;

-- Policies (Adjust as needed for actual auth)
create policy "Public Read" on public."Solicitud_2" for select using (true);
create policy "Public Update" on public."Solicitud_2" for update using (true);

create policy "Public Read" on public."Solicitud_3" for select using (true);
create policy "Public Update" on public."Solicitud_3" for update using (true);

-- Example Insert for testing
-- insert into "Solicitud_2" (numero_operacion, nombre) values ('8492', 'Certificado de Matrimonio');
