-- =====================================================
-- MIGRATION: User Authentication System Setup
-- =====================================================
-- This migration sets up the user authentication system
-- with profiles table and updates existing tables to
-- support user relationships (one-to-many)
-- =====================================================

-- =====================================================
-- 1. CREATE PROFILES TABLE
-- =====================================================
-- This table extends auth.users with additional profile info

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  nombre TEXT,
  apellido TEXT,
  telefono TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for profiles
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Trigger to auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, nombre, apellido, telefono)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'nombre',
    NEW.raw_user_meta_data->>'apellido',
    NEW.raw_user_meta_data->>'telefono'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists and recreate
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =====================================================
-- 2. CREATE/UPDATE ESTUDIOS_TITULOS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.estudios_titulos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  numero_operacion TEXT UNIQUE,
  tipo_propiedad TEXT,
  finalidad_estudio TEXT,
  tiene_servidumbre BOOLEAN,
  tiene_reglamento BOOLEAN,
  cantidad_transacciones INTEGER DEFAULT 0,
  detalle_transacciones JSONB,
  estado TEXT DEFAULT 'En Documentación',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for user_id lookups
CREATE INDEX IF NOT EXISTS idx_estudios_user_id ON public.estudios_titulos(user_id);

-- Enable RLS
ALTER TABLE public.estudios_titulos ENABLE ROW LEVEL SECURITY;

-- RLS Policies (users can only see their own studies)
DROP POLICY IF EXISTS "Users can view own studies" ON public.estudios_titulos;
CREATE POLICY "Users can view own studies" ON public.estudios_titulos
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own studies" ON public.estudios_titulos;
CREATE POLICY "Users can insert own studies" ON public.estudios_titulos
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own studies" ON public.estudios_titulos;
CREATE POLICY "Users can update own studies" ON public.estudios_titulos
  FOR UPDATE USING (auth.uid() = user_id);


-- =====================================================
-- 3. UPDATE SOLICITUD_2 TABLE
-- =====================================================

-- Add user_id column if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'Solicitud_2' 
    AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public."Solicitud_2" ADD COLUMN user_id UUID REFERENCES auth.users(id);
  END IF;
END $$;

-- Update RLS policies
DROP POLICY IF EXISTS "Public Read" ON public."Solicitud_2";
DROP POLICY IF EXISTS "Public Update" ON public."Solicitud_2";
DROP POLICY IF EXISTS "Users can view own solicitudes_2" ON public."Solicitud_2";
DROP POLICY IF EXISTS "Users can modify own solicitudes_2" ON public."Solicitud_2";

CREATE POLICY "Users can view own solicitudes_2" ON public."Solicitud_2"
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own solicitudes_2" ON public."Solicitud_2"
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own solicitudes_2" ON public."Solicitud_2"
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own solicitudes_2" ON public."Solicitud_2"
  FOR DELETE USING (auth.uid() = user_id);


-- =====================================================
-- 4. UPDATE SOLICITUD_3 TABLE
-- =====================================================

-- Add user_id column if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'Solicitud_3' 
    AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public."Solicitud_3" ADD COLUMN user_id UUID REFERENCES auth.users(id);
  END IF;
END $$;

-- Update RLS policies
DROP POLICY IF EXISTS "Public Read" ON public."Solicitud_3";
DROP POLICY IF EXISTS "Public Update" ON public."Solicitud_3";
DROP POLICY IF EXISTS "Users can view own solicitudes_3" ON public."Solicitud_3";
DROP POLICY IF EXISTS "Users can modify own solicitudes_3" ON public."Solicitud_3";

CREATE POLICY "Users can view own solicitudes_3" ON public."Solicitud_3"
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own solicitudes_3" ON public."Solicitud_3"
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own solicitudes_3" ON public."Solicitud_3"
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own solicitudes_3" ON public."Solicitud_3"
  FOR DELETE USING (auth.uid() = user_id);


-- =====================================================
-- 5. CREATE/UPDATE ANTECEDENTES_GENERALES_DOC TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.antecedentes_generales_doc (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  numero_operacion TEXT,
  estado TEXT DEFAULT 'Pendiente',
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
  -- Dynamic columns will be added for document URLs
);

-- Add user_id if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'antecedentes_generales_doc' 
    AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public.antecedentes_generales_doc ADD COLUMN user_id UUID REFERENCES auth.users(id);
  END IF;
END $$;

-- Enable RLS
ALTER TABLE public.antecedentes_generales_doc ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "Users can view own antecedentes" ON public.antecedentes_generales_doc;
CREATE POLICY "Users can view own antecedentes" ON public.antecedentes_generales_doc
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own antecedentes" ON public.antecedentes_generales_doc;
CREATE POLICY "Users can insert own antecedentes" ON public.antecedentes_generales_doc
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own antecedentes" ON public.antecedentes_generales_doc;
CREATE POLICY "Users can update own antecedentes" ON public.antecedentes_generales_doc
  FOR UPDATE USING (auth.uid() = user_id);


-- =====================================================
-- 6. HELPER FUNCTION: Update timestamp
-- =====================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add update triggers
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_estudios_updated_at ON public.estudios_titulos;
CREATE TRIGGER update_estudios_updated_at
  BEFORE UPDATE ON public.estudios_titulos
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- =====================================================
-- DONE!
-- =====================================================
-- Run this SQL in your Supabase SQL Editor
-- Dashboard > SQL Editor > New Query > Paste & Run
-- =====================================================
